### ISSUE TITLE
Player crashed

### ISSUE THREAD

**Issue by jonathonball** [jonathonball/canticle#6]
```
TypeError: Cannot read property 'formats' of undefined
    at YouTubeDl.getInfo (/home/jonathanb/Dropbox/dev/canticle/lib/user_interface/user_interface.js:205:56)
    at done (/home/jonathanb/Dropbox/dev/canticle/node_modules/youtube-dl/lib/youtube-dl.js:286:27)
    at done (/home/jonathanb/Dropbox/dev/canticle/node_modules/youtube-dl/lib/youtube-dl.js:166:37)
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

We should put this in a try catch and add more information to screen log about potential failures.

**Comment by jonathonball** [comment]
This was addressed in Taiga #80
